# Generated by Django 5.2.7 on 2026-01-31 17:22
import phonenumbers
from phonenumbers.phonenumberutil import NumberParseException
from django.db import migrations


def set_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.iterator():
        phone_number = flat.owners_phonenumber
        if not phone_number:
            continue
        try:
            parsed_number = phonenumbers.parse(phone_number, 'RU')
            if phonenumbers.is_valid_number(parsed_number):
                flat.owner_pure_phone = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
                flat.save()
            else:
                print(f'Невалидный номер: {phone_number} (ID квартиры: {flat.id})')
        except NumberParseException as e:
                print(f'Ошибка миграции: {phone_number} (ID квартиры: {flat.id}) - {e}')
        except Exception as e:
            print(f'Неожиданная ошибка: {phone_number} (ID квартиры: {flat.id}) - {e}')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_pure_phone),
    ]
