# Generated by Django 5.2.7 on 2026-01-31 17:22
import phonenumbers
from django.db import migrations


def set_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = flat.owners_phonenumber
        if not phone_number:
            continue
        
        parsed_number = phonenumbers.parse(phone_number, 'RU')
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat.save()
        else:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(set_pure_phone),
    ]
