# Generated by Django 5.2.7 on 2026-02-01 12:20

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.iterator():
        owner, _ = Owner.objects.get_or_create(
            full_name=flat.owner,
            defaults={
                'owners_phonenumber': flat.owners_phonenumber,
                'owner_pure_phone': flat.owner_pure_phone
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_complaint_complaints_text_alter_complaint_flat_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_owners),
    ]
