# Generated by Django 5.2.7 on 2026-02-01 12:49

from django.db import migrations


def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.iterator():
        flats = Flat.objects.filter(owner=owner.full_name)
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20260201_1720'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flats),
    ]
